### ISSUE TITLE
Card & API for User Profiles

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#132]
Authors get a special CTA in their profile, that they can customize. Some ideas:

- Visit my store on..
- My portfolio on..
- Follow me on...

**Comment by dmitrizzle** [comment]
@Jirapong same as user profile:

Name
Profile picture (maybe)
Description (plaintext)
Link --> Button

**Comment by dmitrizzle** [comment]
Related: #218

**Comment by dmitrizzle** [comment]
# Sample API

```json
{  
  "status": "ok",
	"id" : "kyla-medica",
	"name" : "Kyla Medica",
	"image" : "/images/app/film_photo-portrait_of_dmitri_by_betty.jpg",
	"bio-short" : "Short author bio.",
	"link" : {
		"to": "https://www.artsocket.com",
		"template": "website"
	}
}
```

**Comment by dmitrizzle** [comment]
### Edit July 3:  changed "name" to "title" & "short-bio" to "text"

**Comment by kraiwut** [comment]
https://trello.com/c/WAp6B59A/45-api-user
