### ISSUE TITLE
User management & signing with email (no password)

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#133]
- [x] Email (send login 5-digit code & link via email that expires in 10 min)
- [x] Twitter
- [x] Facebook

**Comment by dmitrizzle** [comment]
MVP: Email.

**Comment by dmitrizzle** [comment]
Related #218

**Comment by dmitrizzle** [comment]
# Note
When merging user profile info with Twitter/Facebook login, user preferences made on Analog.Cafe should always get the priority.

For example, if user has already chosen their profile name, it should never be overwritten by data from Twitter or Facebook.

**Comment by kraiwut** [comment]
https://trello.com/c/nPEA8us3/47-api-login
