### ISSUE TITLE
Image upload interface

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#169]
- [x] drag and drop
- [x] file selector
- [x] upload mechanism
- [x] warnings #197 
- [ ] ~convert data-uri strings to *3 optimized JPEG resolutions*~
- [ ] ~ability to download images from URLs~
- [x] upload progress callback/info
- [x] original image files stored together with converted for web files
- [x] in database: author name attached to each uploaded image (auto, non-editable) #330 

***
- [x] image upload together with #231 as an inline button(s)

**Comment by dmitrizzle** [comment]
# Update Jul 13, 2017:
Image JPGs should be converted to *progressive* JPGs
https://optimus.keycdn.com/support/progressive-jpeg/

**Comment by kraiwut** [comment]
https://trello.com/c/FTkb97Am/44-api-image
