### ISSUE TITLE
My Submissions page

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#214]
### Update Aug 1, 2017:
For now we don't need to give users ability to edit their submitted posts.
***
- [x] List of submissions with status
- [ ] ~"Under review" submissions aren't editable~
- [ ] ~Editing either rejected or accepted submissions sends them for review again~
- [ ] ~Accepted and then edited submissions will replace live versions if approved~
- [x] Log Out button

**Comment by dmitrizzle** [comment]
@Jirapong FYI I don't think letting users edit their submitted posts is something that would be easy to build at this moment, considering the current progress.

**Comment by kraiwut** [comment]
https://trello.com/c/71qAZFXQ/43-api-submission
