### ISSUE TITLE
Un-publishing

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#228]
- [x] Policy listed on website: only via email request, takes at least 2 weeks for featured images
- [x] Admin can either/or remove/achieve posts.

**Comment by dmitrizzle** [comment]
Related to #229 - simply reject an approved submission.

**Comment by kraiwut** [comment]
https://trello.com/c/71qAZFXQ/43-api-submission

**Comment by dmitrizzle** [comment]
This needs to be fixed first: https://github.com/roast-cms/analog-cafe-server/issues/232

**Comment by dmitrizzle** [comment]
Complete with https://github.com/dmitrizzle/Analog.Cafe/pull/1041
