### ISSUE TITLE
Notifications for authors (simple emails for submission status and welcome email)

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#229]
- [x] welcome email
- [x] submission status update
- [x] work used in another publication #231 **only if it was posted and approved**

**Comment by dmitrizzle** [comment]
Submissions could be approved or rejected. This status should be changeable.

**Comment by kraiwut** [comment]
https://trello.com/c/HZfrR4y9/49-setup-email
https://trello.com/c/WAp6B59A/45-api-user
https://trello.com/c/71qAZFXQ/43-api-submission
