### ISSUE TITLE
Instant Collaborations API

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#231]
# Instant Collaborations
Instant Collaborations is a list of 8 images that previous authors have approved for this purpose (see #373) and the editor has selected to appear in the image grid (see image below).

All that needs to be done at this point is registering users' preference regarding being open to collaborations in the database & allowing the editor to pick and choose what goes in the grid (#373) and **providing the API** for the <Composer/> to see what those images are, in this format (this is example data):
```
[
  {
    id: "image-froth_658824_ry3-Wh3CZ",
    author: {
      name: "dmitrizzle",
      id: "dmitrizzle"
    }
  },
  {
    id: "image-froth_1546790_b5ff5d48edf8488387d39f64e18b2916",
    author: {
      name: "Betty",
      id: "betty"
    }
  },
  {
    id: "image-froth_623086_BkbGYohCW",
    author: {
      name: "dmitrizzle",
      id: "dmitrizzle"
    }
  },
  {
    id: "image-froth_664111_SynOy3n0b",
    author: {
      name: "dmitrizzle",
      id: "dmitrizzle"
    }
  },
  {
    id: "image-froth_1493506_B1u2qi3CZ",
    author: {
      name: "Betty",
      id: "betty"
    }
  },
  {
    id: "image-froth_660572_rkv4x2h0W",
    author: {
      name: "dmitrizzle",
      id: "dmitrizzle"
    }
  },
  {
    id: "image-froth_701295_Sy1L0ohAW",
    author: {
      name: "dmitrizzle",
      id: "dmitrizzle"
    }
  },
  {
    id: "image-froth_663121_HJILTj2RW",
    author: {
      name: "dmitrizzle",
      id: "dmitrizzle"
    }
  }
]
```

The function that actually inserts the image and adds appropriate credit is complete.
<img width="785" alt="screen shot 2017-11-20 at 11 46 12 am" src="https://user-images.githubusercontent.com/8587882/33002705-6ae05e34-cde8-11e7-9195-ad35fac856c2.png">

**Comment by dmitrizzle** [comment]
### Update July 3:
Added an option to be able to upload monthly assignment image without having to previously have published it.

This could mean this whole module could be as simple as giving "assignment" flag to a set of image ids and allowing to upload images while registering them in database as in #234

**Comment by kraiwut** [comment]
https://trello.com/c/FTkb97Am/44-api-image
