### ISSUE TITLE
Articles containing collaborations/multiple authors should be listable and contain multiple authors attached to them.

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#256]
Articles should be able to have multiple authors when they are part of collaboration. This is the new structure for authorship API:
```
authors: {
    author: {
        id,
        name,
        authorship: "article"
    },
    author: {
        id,
        name,
        authorship: "imagery"
    }
}
```
^^ When the `authorship` is set to "article"  - that's the main author who has composed and submitted the piece. Authors with "imagery" value to `authorship` key are people whose images have been part of the article, although they have not written any text or submitted the work. Example: https://www.analog.cafe/zine/flower-universe-83du - should have this record:

```
authors: [
    author: {
        id: "dmitrizzle",
        name: "dmitrizzle",
        authorship: "article"
    },
    author: {
        id: "chi",
        name: "Chi",
        authorship: "photography"
    }
]
```
## Additionally:
- Articles that have more than one author should be all listed under a filter: `https://api.analog.cafe/list?authorship=collaboration` (for multiple authors) vs `https://api.analog.cafe/list?authorship=solo` (for articles that have one author responsible for all the work)
- Multiple authors listed with commas in rss, only article author in sitemap

Related: #373:

**Comment by dmitrizzle** [comment]
Image URLs from Analog.Cafe **do not need to be converted/reuploaded** @Jirapong

**Comment by kraiwut** [comment]
https://trello.com/c/FTkb97Am/44-api-image
