### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#273]
- [x] API specification required @dmitrizzle @Jirapong 
- [ ] API docs need to be built on /wiki @dmitrizzle

**Comment by dmitrizzle** [comment]
First draft for LISTS: https://github.com/dmitrizzle/Analog.Cafe/blob/develop/public/api/list/index.json

**Comment by dmitrizzle** [comment]
# Example APIs
Article list example API #218 
Article post example API #217 
Author profile example API #132

**Comment by kraiwut** [comment]
https://trello.com/c/BwNxP4bR/25-api-docs

**Comment by dmitrizzle** [comment]
http://api.analog.cafe/api-docs

**Comment by dmitrizzle** [comment]
Needs adding UI: http://mherman.org/blog/2016/05/26/swagger-and-nodejs/#adding-swagger-ui
