### ISSUE TITLE
"Instant Collaborations": admin/editor should be able to select images available in the grid

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#373]
# Instant Collaborations
When the user clicks "Add Image" a grid appears with 8 photographs by other authors that they could include in their work. Those images are selected by admin/editor from the pool of images marked as "Open for Collaborations." Those marks are created by authors when they submit their work and choose to participate:
<img width="373" alt="screen shot 2017-11-20 at 11 30 43 am" src="https://user-images.githubusercontent.com/8587882/33002353-3fe56ef6-cde6-11e7-98ae-f1c80dcb31bf.png">

**Comment by dmitrizzle** [comment]
@Jirapong I was thinking about our conversation yesterday, regarding the list size for "featured" images. That it could be in thousands.

I think that's a bad experience for the user to sift through thousands of images. I don't want to categorize them or have them searchable either (too much work). To fix this, the following should work better:

# Proposal:

- There should be a flag in the admin panel that I can add to images, marking them as "featured"
- The admin panel would have a list of all images that the authors have premitted to be "featured" (see #131 )
- There should be a relatively easy way to see the images (just click a link to the image or something) from admin
- The admin/editor can go through the list and add/remove checkmarks


What do you think?

**Comment by dmitrizzle** [comment]
Related #231

**Comment by kraiwut** [comment]
https://trello.com/c/FTkb97Am/44-api-image
