### ISSUE TITLE
Send/save/API "text only" version of each post

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#392]
Add text only version and add main image/poster as well

**Comment by dmitrizzle** [comment]
As discussed, I will provide the text-only version of each save through the editor (will code to save to LocalStorage, should be picked up by #221 )

**Comment by dmitrizzle** [comment]
Added plaintext to LocalStorage, see #409
<img width="1155" alt="screen shot 2017-07-14 at 2 41 28 pm" src="https://user-images.githubusercontent.com/8587882/28203134-8e9ff5b0-68a2-11e7-9f40-2d0607e1beab.png">

**Comment by kraiwut** [comment]
https://trello.com/c/71qAZFXQ/43-api-submission
