### ISSUE TITLE
Editor's approve, reject & edit view + Author's view for rejected & pending posts

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#446]
- [x] Logged-in editors should be able to set "approved" or "rejected" flags to any post (related: #228 )
- [x] Logged-in editors should be able to see all pending posts
- [x] Logged-in editors should be able to edit any post
***
- [x] Logged-in Authors should be able to see their rejected and pending posts
- [x] Non-logged-in users or users who aren't editors or authors of the given post should never see pending or rejected posts

**Comment by kraiwut** [comment]
https://trello.com/c/71qAZFXQ/43-api-submission
