### ISSUE TITLE
Disable service workers cache

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#517]
> If possible, configure your production environment to serve the generated service-worker.js with (HTTP caching disabled)[http://stackoverflow.com/questions/38843970/service-worker-javascript-update-frequency-every-24-hours]. If that's not possible—GitHub Pages, for instance, does not allow you to change the default 10 minute HTTP cache lifetime—then be aware that if you visit your production site, and then revisit again before service-worker.js has expired from your HTTP cache, you'll continue to get the previously cached assets from the service worker. If you have an immediate need to view your updated production deployment, performing a shift-refresh will temporarily disable the service worker and retrieve all assets from the network.

**Comment by kraiwut** [comment]
https://trello.com/c/Y8Axwqrn/54-cache

**Comment by dmitrizzle** [comment]
Fixed with https://github.com/dmitrizzle/Analog.Cafe/releases/tag/v0.12.0
