### ISSUE TITLE
Email template

### ISSUE THREAD

**Issue by kraiwut** [dmitrizzle/Analog.Cafe#597]
need following email templates
----------------------
- [x] welcome email
- [x] submission status
- [ ] featured image
- [x] image has been used
- [x] login email

**Comment by dmitrizzle** [comment]
@kraiwut what's the difference between "image has been used" and "featured image"?

**Comment by dmitrizzle** [comment]
All except one (see my q above) complete under the sendgrid account templates:

<img width="873" alt="screen shot 2017-09-23 at 4 03 19 pm" src="https://user-images.githubusercontent.com/8587882/30771746-c7c0507a-a078-11e7-9dbd-746fee80bbe9.png">
