### ISSUE TITLE
User ID for users with email exposes their info

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#791]
Users created with email sign-in have their ID as the email. This is not good as it will expose their private contact info as a URL to their profile.

Their ID should be generated as follows:
handle (everything before @ sign) and short random string. So for dmitri@google.com it should be `dmitri987fds`

Let's talk how those IDs are generated for Facebook and Twitter contact also.

**Comment by ice5050** [comment]
Okay!, now the IDs are generated with the username from Twitter and display name from Facebook, then removing all characters after `@` and replace all non-alphanumeric character with `.`.

I will update generating ID from email with random short string as well.
