### ISSUE TITLE
What's the difference between contributor and member?

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#814]

**Comment by ice5050** [comment]
For now, there is no difference between them.

**Comment by dmitrizzle** [comment]
Do you plan to have a difference between the two in the future? OR should we pick one and stick with it for consistency?

**Comment by dmitrizzle** [comment]
Supposed to be:

member > contributor (after successful published article) > editor > admin

**Comment by dmitrizzle** [comment]
moved to https://github.com/roast-cms/analog-cafe-server/issues/236
