### ISSUE TITLE
Reproduce poster isn't first image issue

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#854]
Sometimes poster isn't the first image in the submission. Need to find a reproducible way for that to happen so it could be fixed.

**Comment by dmitrizzle** [comment]
It seems that the first image uploaded might make it to be the poster - which is dictated by connection and image size.

**Comment by dmitrizzle** [comment]
More test ideas:
- [ ] When the very first image is a featured image with no text above it
- [ ] On production only

**Comment by dmitrizzle** [comment]
I've noticed that the poster is the first image uploaded to cloudinary. This might be it.

**Comment by ice5050** [comment]
It worked for me. Here's the submission with the first image being a featured image with no text above it. https://www.analog.cafe/submissions/testing-the-poster-issue-1-7624

**Comment by dmitrizzle** [comment]
Another possible scenario to test:

There are images in the post already, the poster has been generated, the submission has been uploaded. It is then being edited and new images are added below. The poster image changes to one of the new images in the post.

**Comment by dmitrizzle** [comment]
moved to https://github.com/roast-cms/analog-cafe-server/issues/231
