### ISSUE TITLE
Use dedicated render lib for Slate Value

### ISSUE THREAD

**Issue by dmitrizzle** [dmitrizzle/Analog.Cafe#968]
Currently the Slate Value is rendered with Editor, which requires a lot of extra weight, including Immutable. A tool like https://gist.github.com/wmertens/0b4fd66ca7055fd290ecc4b9d95271a9 should help a lot with weight reduction (might save 50kb+ for non-editing users)

cc https://github.com/ianstormtaylor/slate/issues/1951
cc https://github.com/roast-cms/french-press-editor

**Comment by wmertens** [comment]
I think it saves more than that - gzipped sizes are: slate 57kb, slate-react 28kb, immutable 27kb, together that's >100KB and for decent mobile connections you want to keep the total JS gzipped below 400KB.

**Comment by dmitrizzle** [comment]
Youp, very excited to get it set up! But I need some help from you @wmertens (if you got some free time, of course). On your gist:

> Can't seem to make it work, keep getting Error: No serializer defined for node of type "paragraph". I'm using https://github.com/roast-cms/french-press-editor/blob/develop/src/rules.js as rules. Am I doing something wrong?

**Comment by wmertens** [comment]
you need to have `serialize` rules, that ruleset only has `deserialize`

**Comment by dmitrizzle** [comment]
Thank you, will try tonight 👍

**Comment by dmitrizzle** [comment]
It works! Thank you for the tip.
https://gist.github.com/wmertens/0b4fd66ca7055fd290ecc4b9d95271a9

**Comment by dmitrizzle** [comment]
Reduced bundle size for the general user-facing pages by over 30%.
